sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build dev branch only
script:
  - yarn --frozen-lockfile --production
  - npm install lodash.reduce
  - npm install lodash.filter
  - npm install lodash.reject
  - npm install lodash.flatten
  - npm install lodash.some
  - npm install lodash.defaults
  - npm install lodash.foreach
  - npm install lodash.bind
  - npm install css-select
  - npm install lodash.map
  - npm install lodash.assignin
  - npm install lodash.merge
  - npm install lodash.pick
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexo
  local-dir: public
