sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build dev branch only
script:
  - npm install lodash.reduce --frozen-lockfile
  - npm install lodash.filter --frozen-lockfile
  - npm install lodash.reject --frozen-lockfile
  - npm install lodash.flatten --frozen-lockfile
  - npm install lodash.some --frozen-lockfile
  - npm install lodash.defaults --frozen-lockfile
  - npm install lodash.foreach --frozen-lockfile
  - npm install lodash.bind --frozen-lockfile
  - npm install css-select --frozen-lockfile
  - npm install lodash.map --frozen-lockfile
  - npm install lodash.assignin --frozen-lockfile
  - npm install lodash.merge --frozen-lockfile
  - npm install lodash.pick --frozen-lockfile
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexo
  local-dir: public
